stages:
  - build
  - deploy

#
# BUILD APP
#

build_app:
  stage: build
  image: node:22-alpine
  artifacts:
    paths:
      - .env
      - nest_desktop
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  before_script:
    - touch .env
    - VERSION="$(node -p "require('./package.json').version")"
    - |-
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        echo "__version__ = '${VERSION}'" >> nest_desktop/__init__.py
        echo "DOCKER_TAG='${VERSION}'" >> .env
      else
        PYTHON_VERSION="$(node -p "var v = require('./package.json').version.split('-'); [v[0], {alpha: 'a', beta: 'b', dev: 'dev', rc: 'rc'}[v[1]]].join('.')")"
        echo "__version__ = '${PYTHON_VERSION}${CI_PIPELINE_IID}'" >> nest_desktop/__init__.py
        echo "DOCKER_TAG='${VERSION}.${CI_PIPELINE_IID}'" >> .env
      fi
    - yarn install
  script:
    - yarn build
    - cat nest_desktop/__init__.py
    - cat .env
  tags:
    - docker-runner
    - read-only

#
# DEPLOY PYTHON PACKAGE
#

deploy_pypi:
  stage: deploy
  image: python:3.12
  needs:
    - build_app
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
  before_script:
    - python setup.py sdist bdist_wheel
    - pip install twine
  script:
    - |-
      if [[ $CI_COMMIT_BRANCH != "main" ]]; then
        TWINE_PASSWORD=${TESTPYPI_ACCESS_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --repository testpypi dist/*
      else
        TWINE_PASSWORD=${PYPI_ACCESS_TOKEN} TWINE_USERNAME=__token__ python -m twine upload dist/*
      fi
  tags:
    - docker-runner
    - read-only

#
# DEPLOY DOCKER IMAGE ON EBRAINS
#

deploy_docker_ebrains:
  stage: deploy
  image: ubuntu:22.04
  needs:
    - build_app
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
  before_script:
    - source .env
    - echo "${EBRAINS_DOCKER_REGISTRY_TOKEN}" | docker login -u ${EBRAINS_DOCKER_REGISTRY_USER} --password-stdin docker-registry.ebrains.eu
  script:
    - docker build -f docker/Dockerfile -t docker-registry.ebrains.eu/nest/nest-desktop:${DOCKER_TAG} .
    - |-
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        docker tag docker-registry.ebrains.eu/nest/nest-desktop:${DOCKER_TAG} docker-registry.ebrains.eu/nest/nest-desktop:${DOCKER_TAG%.*}
        docker tag docker-registry.ebrains.eu/nest/nest-desktop:${DOCKER_TAG} docker-registry.ebrains.eu/nest/nest-desktop:latest
      else
        docker tag docker-registry.ebrains.eu/nest/nest-desktop:${DOCKER_TAG} docker-registry.ebrains.eu/nest/nest-desktop:dev
      fi
    - docker push docker-registry.ebrains.eu/nest/nest-desktop --all-tags
  after_script:
    - docker logout docker-registry.ebrains.eu
  tags:
    - shell-runner
    - read-only

#
# DEPLOY DOCKER IMAGE ON DOCKER HUB
#

deploy_docker_hub_nest:
  stage: deploy
  image: ubuntu:24.04
  needs:
    - build_app
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
  before_script:
    - source .env
    - echo "${DOCKER_HUB_ACCESS_TOKEN}" | docker login -u ${DOCKER_HUB_ACCESS_USER} --password-stdin
  script:
    - docker build -f docker/Dockerfile -t nest/nest-desktop:${DOCKER_TAG} .
    - |-
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        docker tag nest/nest-desktop:${DOCKER_TAG} nest/nest-desktop:${DOCKER_TAG%.*}
        docker tag nest/nest-desktop:${DOCKER_TAG} nest/nest-desktop:latest
      else
        docker tag nest/nest-desktop:${DOCKER_TAG} nest/nest-desktop:dev
      fi
    - docker push nest/nest-desktop --all-tags
  after_script:
    - docker logout
  tags:
    - shell-runner
    - read-only
